---
version: '3'
services:
  esphome:
    container_name: esphome
    hostname: esphome
    image: "esphome/esphome:${ESPHOME_VERSION:-2025.9.1}"
    # This image is 50% bigger (about 643Mb).
    #image: esphome/esphome:2024.12.4
    volumes:
      # Note that the expected working directory on the docker host is the
      # platformio project root directory (this external component project).
      # Environment variables allow you to change some of the directory mappings,
      # but keep in mind that building/testing this component or running any of the
      # included scripts, from anywhere other than the project root directory,
      # may not produce the expected results.
      #
      # Directory where platformio will store downloaded source code and library files.
      # It appears that platformio is looking in /root within the container
      # for the .platformio, so we're mapping the host .platformio to /root/.platformio
      # within the container, and also to /DynamicCron/.platformio .
      # NOTE: esphome 2024.12 has started using their own fork of a portion
      # of the source code that used to be pulled directly from the platformio project.
      # See https://esphome.io/changelog/2024.12.0/
      # So now we should test/build  dynamic-cron using the .platformio dir
      # that is generated from esphome. Make sure you define this env var
      # as something like '/mnt/efs/esphome/.platformio'.
      - "${DOT_PLATFORMIO:-$PWD/.platformio}:/root/.platformio:rw"
      - "${DOT_PLATFORMIO:-$PWD/.platformio}:/DynamicCron/.platformio:rw"
      #
      # Directory where platformio will output build and firmware files.
      - "${DOT_PIO:-$PWD/.pio}:/DynamicCron/.pio:rw"
      #
      # Maps the location of the external component project directory on the host.
      - "$PWD:/DynamicCron:rw"
      #
      # The .src/ directory is where platformio will look for esphome sourc files.
      # Since we're using the esphome docker image, that directory is /esphome within the container.
      # Disabled this in favor of a container startup script that inserts a symlink to /esphome.
      #- "${SRC_DIR:-$PWD/.src}:/esphome:ro"
      #
      # Specifies where esphome will write build operations to.
      - "${DOT_ESPHOME:-$PWD/.esphome_build}:/DynamicCron/test/esphome_config/.esphome:rw"
      # Secrets file for the esphome test project yaml config.
      - "$PWD/.secrets.yaml:/DynamicCron/test/esphome_config/secrets.yaml"
      #
      # Enables timezone resolution.
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: America/Los_Angeles
    # We're overriding the esphome/esphome image entrypoint of "/entrypoint.sh",
    # so we can start up the container as a bash session.
    entrypoint: [""]
    # If you don't provide a command when launching the docker container,
    # this will default to the original behavior of the esphome/esphome image.
    # It will launch the esphome-dashboard app.
    command: ["/entrypoint.sh","dashboard","/config"]
